# Elements of this Makefile were taken from the provided Makefile in HW1

FILES = Makefile scanner.mll parser.mly ast.ml toplevel.ml 

scanner_parser : scanner.mll parser.mly ast.ml toplevel.ml README 
	zip Compost.zip scanner.mll parser.mly ast.ml toplevel.ml README \
	test_files run_tests.bash README 

